Add normative references for 3 json schema versions
w3c/vc-json-schema pull request #170
Opened 2023-07-05 20:09 UTC by decentralgabe

fix #133

2023-07-05 20:10 UTC, decentralgabe commented
![Screenshot 2023-07-05 at 1 09 58 PM](https://github.com/w3c/vc-json-schema/assets/7622243/1f85626e-8643-40c3-8ba9-a4632c541498)

2023-07-05 20:22 UTC, OR13 commented on index.html
> +                      • <a href="https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02">JSON Schema: A Media Type for Describing JSON Documents</a></br>
not sure about all these IETF refs, prefer to not mix IETF and OpenJS refs for the same standard, I suggest not referring to IETF drafts at all.

2023-07-05 20:23 UTC, OR13 requested changes
Remove the IETF refs, just use OpenJS

2023-07-05 20:25 UTC, decentralgabe commented
updated 
![Screenshot 2023-07-05 at 1 25 25 PM](https://github.com/w3c/vc-json-schema/assets/7622243/40c08af3-dacd-48f2-9df1-b2d7d9b06cfc)

2023-07-05 20:32 UTC, OR13 approved these changes

2023-07-05 20:32 UTC, OR13 commented
Given that we will be forced to review this all when we advance to CR, any reason not to merge this now?

2023-07-06 14:00 UTC, iherman commented
> Given that we will be forced to review this all when we advance to CR, any reason not to merge this now?

I agree.

Actually: [this blog](https://json-schema.org/blog/posts/future-of-json-schema) on the stability of JSON Schemas is interesting (and important). As we get closer to CR (or even PR) we may have a stable reference that we can rely on once and for all. (I missed this particular blog, my attention was just called on it right now.)

In the meantime, we can simply go on with this PR.

2023-07-06 17:02 UTC, merged