Update term definitions according to the core vocab
w3c/vc-json-schema pull request #185
Opened 2023-07-25 20:27 UTC by decentralgabe

Fix #182

2023-07-25 21:13 UTC, andresuribe87 approved these changes

2023-07-25 22:39 UTC, OR13 approved these changes

2023-07-25 22:40 UTC, OR13 requested changes
Seems like the term definitions should be to the vocabulary.

Cc@iherman

2023-07-26 06:32 UTC, iherman requested changes
Unfortunately, that is incorrect... I propose to change the sentences as follows:

```html
<p>
This term is part of the 
<a href="https://www.w3.org/ns/credentials#JsonSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
</p>
…
<p>
This term is part of the 
<a href="https://www.w3.org/ns/credentials#VerifiableCredentialSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
</p>
```

I do not believe referring to the JSON-LD spec's term definition brings anything here, so I removed that reference, too.

Of course, the URL-s must be updated if the final term names change.

(GitHub does not let me propose a direct edit to the full sentence, hence this comment.)

2023-07-26 14:45 UTC, TallTed commented on index.html
> +               is <code>https://www.w3.org/TR/vc-json-schema#JsonSchema2023</code>.
The slashless URI gets a `302 Found` redirect to the slashed URI, where the fragment does not resolve.

The text found in that document always reads as the mixed case `JsonSchema2023`, but the fragment identifier for the section where it is defined is the lowercase [`#jsonschema2023`](https://www.w3.org/TR/vc-json-schema/#jsonschema2023), where it says --
> This [term definition](https://www.w3.org/TR/json-ld/#dfn-term-definition) is https://www.w3.org/ns/credentials#JsonSchema2023.

-- which gets a `302 Found` redirect to `https://www.w3.org/ns/credentials/` which gets a `404 Not Found`. 

This is confusing to me, and I've been working with all this stuff for quite a while. It seems that anyone new to any of this material who encounters the above will quickly throw up their hands and walk away.

2023-07-26 14:46 UTC, TallTed commented on index.html
> +               is <code>https://www.w3.org/TR/vc-json-schema#VerifiableCredentialSchema2023</code>.
Similar to comments above on `JsonSchema2023`.

2023-07-26 15:39 UTC, decentralgabe commented
updated based on @iherman's comment.

@TallTed I notice the 404 as well, but I trust @iherman's suggestion. Maybe it'll be resolved after the core data model PR is merged?

2023-07-26 16:27 UTC, iherman commented
Sorry @TallTed and @decentralgabe I screwed up. The right URLs should be

- https://www.w3.org/2018/credentials/#JsonSchema2023
- https://www.w3.org/2018/credentials/#VerifiableCredentialSchema2023

ie:

```html
<p>
This term is part of the 
<a href="https://www.w3.org/2018/credentials/#JsonSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
</p>
…
<p>
This term is part of the 
<a href="https://www.w3.org/2018/credentials/#VerifiableCredentialSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
</p>
```

Sorry about the confusion.

2023-07-26 19:16 UTC, decentralgabe commented
updated

2023-07-31 20:24 UTC, decentralgabe commented on index.html
> +               <a href="https://www.w3.org/2018/credentials/#VerifiableCredentialSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
```suggestion
               <a href="https://www.w3.org/2018/credentials/#VerifiableCredentialSchema2023">Verifiable Credentials Vocabulary v2.0</a>.
             </p>
```

2023-07-31 20:24 UTC, decentralgabe commented on index.html
> +             </p>
```suggestion
            </p>
```

2023-08-01 06:42 UTC, iherman approved these changes

2023-08-01 06:45 UTC, iherman commented
@OR13 
> Seems like the term definitions should be to the vocabulary.
> 
> Cc@iherman

@OR13, @decentralgabe, also with https://github.com/w3c/vc-data-model/pull/1218, I believe this PR can be merged.

2023-08-01 12:59 UTC, OR13 approved these changes

2023-08-01 15:55 UTC, merged