Media types for plain json schema, JWT, and SD-JWT
w3c/vc-json-schema pull request #198
Opened 2023-08-09 18:38 UTC by decentralgabe

fix #157

2023-08-09 18:43 UTC, OR13 commented on index.html
> +               <h2><code>application/vc+ld+jwt+schema+json</code></h2>
I don't think you need this... in the case you are dereferencing a "JsonSchemaCredential" the response type will be:

1. `application/vc+ld+json` in the case of data integrity proof.
2. `application/vc+ld+json+jwt` or `application/vc+ld+json+sd-jwt` in the case of vc-jose-cose

2023-08-09 18:44 UTC, OR13 commented on index.html
> +            </section>
```suggestion
```

2023-08-09 18:48 UTC, OR13 requested changes
Adjust PR to acknowledge the response type for dereferencing... expecting to see at least the following media types acknowledged, but none of them will be registered by this spec.

For type: "JsonSchema": 

- `application/schema+json` or `application/json`
- `application/openapi+yaml` (maybe) or `application/yaml`  (maybe)

For type: "JsonSchemaCredential": 

- `application/vc+ld+json` 
- `application/vc+ld+json+jwt` 
- `application/vc+ld+json+sd-jwt`

2023-08-09 19:07 UTC, decentralgabe commented on index.html
> +            </section>
removed

2023-08-09 19:08 UTC, decentralgabe commented on index.html
> +          <section class="normative">
just updated formatting here...

2023-08-09 19:44 UTC, andresuribe87 commented on index.html
> +                  JsonSchemaCredential</a> type, as registered in the [[VC-DATA-MODEL-2]] and [[VC-JWT]] specifications.
```suggestion
                  JsonSchemaCredential</a> type, as registered in the [[VC-DATA-MODEL-2]] and [[VC-JOSE-COSE]] specifications.
```

2023-08-09 19:44 UTC, andresuribe87 commented on index.html
> +                  <code>application/vc+ld+json+jwt</code>, and <code>application/vc+ld+json+sd-jwt</code> Media Types
`application/vc+ld+json+sd-jwt` is registered in https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-05.html#section-12.2

I'm not sure how to reference that spec though.

2023-08-09 20:06 UTC, decentralgabe commented on index.html
> +                  JsonSchemaCredential</a> type, as registered in the [[VC-DATA-MODEL-2]] and [[VC-JOSE-COSE]] specifications.
```suggestion
                  JsonSchemaCredential</a> type, as registered in the [[VC-DATA-MODEL-2]], [[VC-JOSE-COSE]], and [[SD-JWT]] specifications respectively.
```

2023-08-09 20:15 UTC, andresuribe87 approved these changes

2023-08-09 20:17 UTC, OR13 commented on index.html
> +            constructed to specify application to subsets of a given credential.
wording a bit awk

2023-08-09 20:17 UTC, OR13 approved these changes

2023-08-09 20:21 UTC, decentralgabe commented on index.html
> +            Implementers may wish to validate certain sections or properties of a
```suggestion
            Implementers may wish to validate certain properties in a 
```

2023-08-09 20:22 UTC, decentralgabe commented on index.html
> +            constructed to specify application to subsets of a given credential.
```suggestion
            constructed to validate subsets of a credential's data.
```

2023-08-09 20:22 UTC, decentralgabe commented on index.html
> +            constructed to specify application to subsets of a given credential.
updated

2023-08-14 17:43 UTC, decentralgabe commented on index.html
> +               <pre class="example vc" title="Example Verifiable Credential - validations Success">
```suggestion
               <pre class="example vc-jwt" title="Example Verifiable Credential - validations Success">
```

2023-08-14 18:07 UTC, merged